### PR TITLE
Fixed the naming convention.

### PR DESCRIPTION
**Pull request by Krakonos**
Some of the footprints were badly named, according to the convention described in the main repository. I fixed that, now it works as expected.

### CODE REVIEW

**Comment by CarlPoirier** [comment]
Thank you. Would you like to fix the 3d model names as well? This implies the path in each of these files and the mentioned file name in the repo kicad-library. If you would like to, please open a pull request for this repo as well and reference each other so that we make sure to merge them both.

**Comment by Krakonos** [comment]
Done.

By the way, there are still some SOT23*, and I have not renamed them, since they 
exist onder both names (unfortunately, they are not the same). Is there any 
reason for them being there? I think one of them may be better, and would like 
to keep the better one, but I don't think I can decide that. 

Another thing is, is there any reason in having a lot of Housings_* packages? I 
would consider moving this stuff into Packages_SMD, since that is the place I 
would look for these common smd footprints.

Thanks!

On Sat, Mar 07, 2015 at 12:21:29PM -0800, CarlPoirier wrote:
> Thank you. Would you like to fix the 3d model names as well? This implies the 
> path in each of these files and the mentioned file name in the repo 
> kicad-library. If you would like to, please open a pull request for this repo 
> as well and reference each other so that we make sure to merge them both.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/KiCad/Housings_SOT-23_SOT-143_TSOT-6.pretty/pull/3#issuecomment-77708084

-- 
S pozdravem Ladislav L�ska                          <laska@kam.mff.cuni.cz>
Katedra Aplikovan� Matematiky, MFF UK               tel.: +420 739 464 167

**Comment by michal777** [comment]
Yes, I forgot to remove duplicated SOT-23_5 and SOT-23_6. Could you remove SOT-23-5/6 and rename SOT23-5/6 to SOT-23_5/6 (keep these with circles as 1 pin marker)? It would be also nice to remove the word "Housings" from TSOT6... name.

There is some mess in transistors. SMD_Packages is going to be removed. I think it would be better to keep packages of transistors in two libraries: Transistors_THT and Transistors_SMD. Also other packages derived from packages for transistors (like two pin TO-92, six pin SOT-23, five pin TO-220) could be in these libraries and it will be relatively clear.
@CarlPoirier - what do you think about it?

**Comment by Krakonos** [comment]
Excellent! I will do that tomorrow, now it's time for some sleep.

On Sat, Mar 07, 2015 at 02:39:24PM -0800, michal777 wrote:
> Yes, I forgot to remove duplicated SOT-23_5 and SOT-23_6. Could you remove 
> SOT-23-5/6 and rename SOT23-5/6 to SOT-23_5/6 (keep these with circles as 1 
> pin marker)? It would be also nice to remove the word "Housings" from TSOT6... 
> name.
> 
> There is some mess in transistors. SMD_Packages is going to be removed. I 
> think it would be better to keep packages of transistors in two libraries: 
> Transistors_THT and Transistors_SMD. Also other packages derived from packages 
> for transistors (like two pin TO-92, six pin SOT-23, five pin TO-220) could be 
> in these libraries and it will be relatively clear.
> @CarlPoirier - what do you think about it?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/KiCad/Housings_SOT-23_SOT-143_TSOT-6.pretty/pull/3#issuecomment-77714479

-- 
S pozdravem Ladislav L�ska                          <laska@kam.mff.cuni.cz>
Katedra Aplikovan� Matematiky, MFF UK               tel.: +420 739 464 167

**Comment by CarlPoirier** [comment]
Whichever SOT-23 are kept, they should be redesigned to better fit the KLC. I'll merge this first.

I'm fine with the Transistors_SMD.pretty and Transistors_ThroughHole.pretty libraries, but that is another story altogether.

**Comment by CarlPoirier** [comment]
Thanks Ladislav for your contribution.

**Pull request merged**
